"""Rice variety catalog (seed v2).

Durations are seed-to-harvest days exactly as published by the cited source; when a source gives a
range we keep it (`duration_range`) and model the midpoint. Release years are only filled in when the
TNAU release list and the crop production guide agree. Entries whose duration could not be confirmed
against a published source are not included; farmers can add those through "Ask AI", which is labelled
as unverified.
"""

TN_CPG_RICE = {
    "title": "Crop Production Guide 2020 — Rice: season, varieties and particulars of varieties",
    "publisher": "Department of Agriculture, Tamil Nadu & TNAU",
    "url": "https://tnagriculture.in/dashboard/CPG/01_Rice.pdf",
}
TNAU_RELEASES = {
    "title": "Crop varieties released from TNAU (1921–2024)",
    "publisher": "Tamil Nadu Agricultural University",
    "url": "https://tnau.ac.in/site/research/wp-content/uploads/sites/60/2024/10/Crop-Varieties-Released-1921-2024.pdf",
}
TNAU_RICE_TECH = {
    "title": "Rice technologies developed (varieties, duration)",
    "publisher": "TNAU Centre for Plant Breeding and Genetics",
    "url": "https://tnau.ac.in/site/cpbg/rice-technologies-developed/",
}
TNAU_PRESS_2022 = {
    "title": "TNAU released new crop varieties for 2022 (press note)",
    "publisher": "Tamil Nadu Agricultural University",
    "url": "http://www.agritech.tnau.ac.in/tnaupressnotes/pdf/2022/Press%20note%20-%20TNAU%20New%20Crop%20varieties%202022%20-%20English-2.pdf",
}
TNAU_PRESS_2023 = {
    "title": "TNAU varieties/technologies developed during 2023 (press note)",
    "publisher": "Tamil Nadu Agricultural University",
    "url": "https://agritech.tnau.ac.in/crop_improvement/pdf/TNAU%20Variety%20release%20-%20Eng.pdf",
}
TNAU_TN_VARIETIES = {
    "title": "Paddy varieties of Tamil Nadu (ruling and traditional varieties)",
    "publisher": "TNAU Agritech Portal",
    "url": "http://www.agritech.tnau.ac.in/expert_system/paddy/TNvarieties.html",
}
TNAU_KL_VARIETIES = {
    "title": "Paddy varieties of Kerala",
    "publisher": "TNAU Agritech Portal",
    "url": "https://agritech.tnau.ac.in/expert_system/paddy/KLvarieties.html",
}
TNAU_ITK_TRADITIONAL = {
    "title": "Traditional rice varieties: Mapillai samba and Thuyamalli",
    "publisher": "TNAU Agritech Portal (ITK)",
    "url": "https://agritech.tnau.ac.in/itk/rice_variety_mapillai&thuyamalli.html",
}
RKB_ODISHA_SWARNA = {
    "title": "Swarna (MTU 7029) — variety sheet",
    "publisher": "Rice Knowledge Bank Odisha",
    "url": "https://rkb-odisha.in/wp-content/uploads/2024/09/swarna-mtu-7029-english.pdf",
}
IARI_BASMATI = {
    "title": "Pusa Basmati 1121 / Pusa Basmati 1509",
    "publisher": "ICAR-IARI (via AICRIP centre report)",
    "url": "http://www.icar-iirr.org/AICRIP/Centers/New%20Delhi.pdf",
}

TNAU = "Tamil Nadu Agricultural University (TNAU)"
KAU = "Kerala Agricultural University (KAU)"

SHORT = ["kuruvai", "navarai"]  # TN guide: Kuruvai / Navarai / Sornavari / Kar → short duration
MEDIUM = ["samba", "thaladi"]  # Late samba / Thaladi → medium duration
LONG = ["samba"]  # Samba → long duration
KERALA_SEASONS = "Kerala: Virippu / Mundakan / Puncha"


def _v(name: str, days: tuple[int, int] | int, grain: str | None, group: str, ref: dict, *,
       seasons: list[str] | None = None, aliases: list[str] | None = None, institute: str | None = None,
       year: int | None = None, regions: list[str] | None = None, notes: str | None = None,
       seasons_text: str | None = None, verified: bool = True) -> dict:
    lo, hi = (days, days) if isinstance(days, int) else days
    mid = round((lo + hi) / 2)
    return {
        "name": name, "duration_days": mid, "duration_range": [lo, hi],
        "duration_group": "short" if mid <= 115 else "medium" if mid <= 135 else "long",
        "seasons": seasons or [], "aliases": aliases or [], "grain_type": grain, "group": group,
        "institute": institute, "release_year": year, "regions": regions or [], "notes": notes,
        "seasons_text": seasons_text, "reference": ref, "verified": verified,
    }


TN = ["Tamil Nadu"]

RICE_VARIETIES: list[dict] = [
    # ---- Tamil Nadu releases (TN Crop Production Guide 2020 particulars + TNAU release list) ----
    _v("CO 51", (105, 110), "Medium slender, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=2013,
       regions=TN, notes="ADT 43 / RR 272-1745."),
    _v("MDU 6", (115, 120), "Long slender, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=2015,
       regions=TN),
    _v("TPS 5", 118, "Short bold, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=2014, regions=TN),
    _v("ADT 36", 110, "Medium, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=1980, regions=TN),
    _v("ADT 37", 105, "Short bold, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=1987, regions=TN),
    _v("ADT 43", 110, "Medium slender, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=1998,
       regions=TN, notes="Guide: for Kar / Sornavari / Kuruvai; should not be grown during the cold-weather period."),
    _v("ADT (R) 45", 110, "Medium slender, white", "tn", TN_CPG_RICE, seasons=SHORT, aliases=["ADT 45", "ADT R 45"],
       institute=TNAU, year=2001, regions=TN),
    _v("ASD 16", (110, 115), "Short bold, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=1986,
       regions=["Tamil Nadu", "Kerala"]),
    _v("ASD 18", (105, 110), "Medium slender, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=1991,
       regions=TN),
    _v("ASD 20", 110, "Long slender, white", "tn", TNAU_TN_VARIETIES, seasons=SHORT, institute=TNAU, year=1997,
       regions=TN),
    _v("Anna (R) 4", (105, 110), "Long slender, white", "tn", TN_CPG_RICE, aliases=["Anna 4"], institute=TNAU,
       year=2009, regions=TN, notes="Rainfed direct-seeded and semi-dry rice; drought-affected areas."),
    _v("CORH 3 (hybrid)", (110, 115), "Medium slender, white", "tn", TN_CPG_RICE, seasons=SHORT, aliases=["CORH 3"],
       institute=TNAU, year=2006, regions=TN, notes="Hybrid — buy fresh seed every season."),
    _v("ADT 53", (110, 115), "Medium slender, white", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=2019,
       regions=TN),
    _v("TKM 9", (100, 105), "Short bold, red", "tn", TN_CPG_RICE, seasons=SHORT, institute=TNAU, year=1978, regions=TN),
    _v("TKM 11", (110, 120), "Long slender, white", "tn", TN_CPG_RICE, institute=TNAU, year=1998, regions=TN,
       notes="Recommended for rainfed direct-seeded / semi-dry conditions."),
    _v("TRY (R) 2", (115, 120), "Long slender, white", "tn", TN_CPG_RICE, aliases=["TRY 2"], institute=TNAU,
       year=2001, regions=TN, notes="Suited to salt-affected soils."),
    _v("ADT (R) 48", (94, 99), "Long slender, white", "tn", TN_CPG_RICE, seasons=["kuruvai"], aliases=["ADT 48"],
       institute=TNAU, year=2005, regions=TN),
    _v("MDU 5", (95, 100), "Medium slender, white", "tn", TN_CPG_RICE, seasons=["kuruvai"], institute=TNAU,
       year=1996, regions=TN, notes="Drought tolerant; dry and transplanted conditions."),
    _v("PMK (R) 3", (110, 115), "Long bold, white", "tn", TN_CPG_RICE, aliases=["PMK 3"], institute=TNAU, year=2003,
       regions=TN, notes="Semi-dry / rainfed areas."),
    _v("CO 52", (130, 135), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=2017,
       regions=TN, notes="BPT 5204 / CO (R) 50."),
    _v("TKM 13", 130, "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=2015,
       regions=TN),
    _v("TRY 3", 135, "Medium, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=2010, regions=TN,
       notes="Suited to salt-affected soils."),
    _v("VGD 1", (130, 135), "Short bold, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=2019,
       regions=TN, notes="ADT 43 / Seeraga Samba."),
    _v("ADT 49", (130, 135), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=2011,
       regions=TN),
    _v("CO (R) 50", (130, 135), "Medium, white", "tn", TN_CPG_RICE, seasons=MEDIUM, aliases=["CO 50"],
       institute=TNAU, year=2010, regions=TN),
    _v("ADT 39", (120, 125), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=1988,
       regions=TN),
    _v("ADT 38", (130, 135), "Long slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=1987,
       regions=TN),
    _v("Improved White Ponni", (135, 140), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM,
       aliases=["IWP", "Imp. White Ponni", "White Ponni", "Ponni"], institute=TNAU, year=1986, regions=TN,
       notes="Fine-grain quality rice. Guide: susceptible to blast — plan plant protection."),
    _v("ADT (R) 46", 135, "Long slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, aliases=["ADT 46"],
       institute=TNAU, year=2002, regions=TN),
    _v("CO 43", (135, 140), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=1982,
       regions=TN, notes="Tolerates alkalinity / salinity."),
    _v("Paiyur 1", (135, 140), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU,
       year=1982, regions=TN),
    _v("TPS 3", (135, 140), "Short bold, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=1993,
       regions=TN),
    _v("TNAU Rice Hybrid CO 4", (130, 135), "Medium slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM,
       aliases=["Hybrid CO 4", "CO 4 hybrid"], institute=TNAU, year=2011, regions=TN,
       notes="Hybrid — buy fresh seed every season."),
    _v("TRY 1", (135, 140), "Medium, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=1995,
       regions=TN, notes="Suited to salt-affected soils."),
    _v("ASD 19", (120, 132), "Short slender, white", "tn", TN_CPG_RICE, seasons=MEDIUM, institute=TNAU, year=1995,
       regions=TN),
    _v("ADT 51", 154, "Medium, white", "tn", TN_CPG_RICE, seasons=LONG, institute=TNAU, regions=TN,
       notes="BPT 5204 / Improved White Ponni."),
    _v("CR 1009 Sub1", (150, 155), "Short bold, white", "tn", TN_CPG_RICE, seasons=LONG, institute=TNAU, year=2015,
       regions=TN, notes="Sub1 gene: tolerates short-term submergence (flood-prone areas). Photoperiod-sensitive."),
    _v("ADT 50", 149, "Medium slender, white", "tn", TN_CPG_RICE, seasons=LONG, institute=TNAU, year=2012, regions=TN),
    _v("ADT 44", 148, "Short bold, white", "tn", TNAU_TN_VARIETIES, seasons=LONG, institute=TNAU, year=2000,
       regions=TN),
    _v("CO 53", (115, 120), "Short bold, white", "tn", TNAU_RICE_TECH, institute=TNAU, year=2020, regions=TN,
       notes="Drought tolerant; suited to idli making."),
    _v("ADT 54", (130, 135), None, "tn", TNAU_RICE_TECH, seasons=MEDIUM, institute=TNAU, year=2020, regions=TN,
       notes="Late Samba / Thaladi. Grain quality close to Improved White Ponni; moderately resistant to blast."),
    _v("CO 54", (110, 118), "Medium slender, white", "tn", TNAU_RICE_TECH, seasons=SHORT, institute=TNAU, year=2021,
       regions=TN, notes="Sources give 110–115 and 115–118 days."),
    _v("ADT 55", (110, 115), "Medium slender, white", "tn", TNAU_RICE_TECH, seasons=SHORT, institute=TNAU, year=2021,
       regions=TN),
    _v("TRY 4", (125, 130), "Medium slender, white", "tn", TNAU_RICE_TECH, seasons=MEDIUM, institute=TNAU, year=2021,
       regions=TN, notes="Recommended for salt-affected soils."),
    _v("CO 55", (110, 115), "Medium slender, superfine", "tn", TNAU_PRESS_2022, seasons=SHORT, institute=TNAU,
       regions=TN),
    _v("ADT 57", 115, "Medium slender, white", "tn", TNAU_PRESS_2022, seasons=SHORT, institute=TNAU, year=2022,
       regions=TN),
    _v("TKM 15", (115, 120), "Medium slender, white", "tn", TNAU_PRESS_2022, institute=TNAU, year=2022, regions=TN,
       notes="Drought tolerant; direct sowing under semi-dry conditions in the NE monsoon (Sep–Oct)."),
    _v("TRY 5", (110, 115), "Medium slender, white", "tn", TNAU_PRESS_2022, seasons=["kuruvai", "thaladi", "navarai"],
       institute=TNAU, year=2022, regions=TN, notes="Suited to salt-affected soils."),
    _v("CO 56", (130, 135), "Medium slender, white", "tn", TNAU_PRESS_2023, seasons=MEDIUM, institute=TNAU,
       year=2023, regions=TN),
    _v("Improved Kavuni CO 57", (110, 135), None, "tn", TNAU_PRESS_2023, aliases=["CO 57", "Improved Kavuni"],
       institute=TNAU, year=2023, regions=TN, verified=False,
       notes="Duration approximate: TNAU sources differ (110–115 vs 130–135 days). Photo-insensitive; all seasons."),
    _v("ADT 58", 125, "Medium slender, white", "tn", TNAU_PRESS_2023, seasons=["thaladi"], institute=TNAU, year=2023,
       regions=TN),
    _v("ASD 21", 120, "Short bold, white", "tn", TNAU_PRESS_2023, seasons=["kuruvai"], institute=TNAU, year=2023,
       regions=TN, notes="Early Kar / early Kuruvai / late Pishanam."),
    _v("CO 58", (118, 124), "Long slender, white", "tn", TNAU_RICE_TECH, institute=TNAU, year=2024, regions=TN),
    _v("CORH 5 (hybrid)", (120, 125), "Medium slender, white", "tn", TNAU_RICE_TECH, aliases=["CORH 5"],
       institute=TNAU, year=2024, regions=TN, notes="Two-line hybrid — buy fresh seed every season."),
    # ---- National / other-state varieties widely grown in South India ----
    _v("BPT 5204", 150, "Medium slender, white", "national", TNAU_TN_VARIETIES, seasons=LONG,
       aliases=["Samba Mahsuri", "Samba Masuri", "Sona Masuri", "Sona Mahsuri"],
       institute="ANGRAU, Andhra Pradesh", regions=["Andhra Pradesh", "Telangana", "Tamil Nadu", "Karnataka"],
       notes="Popularly sold as Samba / Sona Masuri. Blast resistant (TNAU); fine grain."),
    _v("CR 1009", (155, 160), "Short bold, white", "national", TN_CPG_RICE, seasons=LONG, aliases=["Ponmani"],
       institute="ICAR-NRRI (CRRI), Cuttack", regions=TN, notes="Pankaj / Jagannath. Photoperiod-sensitive."),
    _v("IR 20", (130, 135), "Medium slender, white", "national", TNAU_TN_VARIETIES, seasons=MEDIUM,
       institute="IRRI", regions=TN),
    _v("IR 36", 120, "Medium, white", "national", TNAU_TN_VARIETIES, institute="IRRI", regions=TN,
       notes="Resistant to brown plant hopper (TNAU)."),
    _v("IR 64", (115, 120), "Long slender, white", "national", TNAU_TN_VARIETIES, seasons=SHORT, institute="IRRI",
       regions=TN),
    _v("Swarna (MTU 7029)", (145, 150), "Medium bold, white", "national", RKB_ODISHA_SWARNA,
       aliases=["MTU 7029", "Swarna", "Lal Swarna"], institute="ANGRAU (RARS Maruteru)",
       regions=["Andhra Pradesh", "Odisha", "West Bengal", "Bihar", "Chhattisgarh"], seasons=["kharif"]),
    _v("Jaya", (120, 125), "Long bold, white", "national", TNAU_KL_VARIETIES, regions=["Kerala", "Karnataka"],
       seasons_text=KERALA_SEASONS),
    _v("Pusa Basmati 1121", 145, "Extra-long slender, aromatic (basmati)", "national", IARI_BASMATI,
       aliases=["PB 1121", "1121 basmati"], institute="ICAR-IARI, New Delhi",
       regions=["Punjab", "Haryana", "Uttar Pradesh", "Delhi"], seasons=["kharif"],
       notes="Basmati GI region is the Indo-Gangetic plains; not suited to Tamil Nadu conditions for basmati quality."),
    _v("Pusa Basmati 1509", (115, 120), "Extra-long slender, aromatic (basmati)", "national", IARI_BASMATI,
       aliases=["PB 1509"], institute="ICAR-IARI, New Delhi", regions=["Punjab", "Haryana", "Uttar Pradesh", "Delhi"],
       seasons=["kharif"], notes="Pusa 1121 / Pusa 1301."),
    # ---- Kerala (KAU) — TNAU Agritech "Paddy varieties of Kerala" ----
    _v("Jyothi (PTB 39)", (110, 125), "Long bold, red (matta-type)", "kerala", TNAU_KL_VARIETIES,
       aliases=["Jyothy", "PTB 39", "Matta", "Kerala Matta", "Palakkadan Matta", "Red rice", "Rosematta"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS,
       notes="Widely grown red-kernel variety used for matta rice."),
    _v("Kanchana (PTB 50)", (105, 110), "Long bold, red (matta-type)", "kerala", TNAU_KL_VARIETIES,
       aliases=["PTB 50", "Matta", "Kerala Matta", "Red rice"], institute=KAU, regions=["Kerala"],
       seasons_text=KERALA_SEASONS),
    _v("Aathira (PTB 51)", (120, 130), "Short bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 51", "Athira"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Aiswarya (PTB 52)", (120, 125), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 52", "Aishwarya"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Uma (MO 16)", (115, 135), "Medium bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 16", "Matta"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS,
       notes="115–120 days in Mundakan, 120–135 days in Virippu."),
    _v("Kairali (PTB 49)", (110, 115), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 49"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Annapurna (PTB 35)", (95, 100), "Short bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 35"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Rohini (PTB 36)", (85, 105), "Long bold, white", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 36"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Triveni (PTB 38)", (100, 105), "Long bold, white", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 38"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Swarnaprabha (PTB 43)", (105, 110), "Long bold, white", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 43"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Mattatriveni (PTB 45)", (100, 105), "Medium bold, red", "kerala", TNAU_KL_VARIETIES,
       aliases=["PTB 45", "Matta Triveni", "Matta"], institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Harsha (PTB 55)", (105, 110), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 55"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Varsha (PTB 56)", (110, 115), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 56"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Aswathy (PTB 37)", (120, 125), "Long bold, white", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 37"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Sabari (PTB 40)", (130, 135), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 40"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Bharathy (PTB 41)", (120, 125), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 41"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Karthika (MO 7)", (105, 125), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 7"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Aruna (MO 8)", (100, 110), "Medium bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 8"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Makom (MO 9)", (100, 110), "Short bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 9"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Remya (MO 10)", (110, 120), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 10"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Kanakom (MO 11)", (120, 125), "Medium bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 11"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Remanika (MO 15)", (100, 105), "Short bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 15"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Revathy (MO 17)", (105, 110), "Medium bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 17"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Krishnanjana (MO 19)", (105, 110), "Medium bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 19"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Bhadra (MO 4)", (120, 125), "Red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 4"], institute=KAU,
       regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Pavizham (MO 6)", (115, 120), "Short bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["MO 6"],
       institute=KAU, regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Hraswa", (75, 80), "Medium bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["Cul 24-20"], institute=KAU,
       regions=["Kerala"], seasons_text=KERALA_SEASONS),
    _v("Mangalamahsuri (PTB 53)", (140, 145), "Medium slender, red", "kerala", TNAU_KL_VARIETIES,
       aliases=["PTB 53"], institute=KAU, regions=["Kerala"], seasons_text="Kerala: Mundakan"),
    _v("Karuna (PTB 54)", (140, 145), "Long bold, red", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 54"],
       institute=KAU, regions=["Kerala"], seasons_text="Kerala: Mundakan"),
    _v("Neeraja (PTB 47)", (140, 150), "White", "kerala", TNAU_KL_VARIETIES, aliases=["PTB 47"], institute=KAU,
       regions=["Kerala"], seasons_text="Kerala: Mundakan"),
    _v("Pranava", (130, 135), "Medium slender, white", "kerala", TNAU_KL_VARIETIES, regions=["Kerala"],
       seasons_text="Kerala: Mundakan"),
    _v("Vyttila 1", 115, "Red", "kerala", TNAU_KL_VARIETIES, aliases=["Chootupokkali", "Pokkali"], regions=["Kerala"],
       seasons_text=KERALA_SEASONS, notes="Pokkali-type, coastal saline fields."),
    _v("Vyttila 3", (110, 115), "Red", "kerala", TNAU_KL_VARIETIES, aliases=["Pokkali"], regions=["Kerala"],
       seasons_text=KERALA_SEASONS, notes="Pokkali-type, coastal saline fields."),
    # ---- Traditional varieties (landraces; durations vary between seed lots) ----
    _v("Seeraga Samba", (125, 130), "Very small, fine, aromatic", "traditional", TNAU_TN_VARIETIES, seasons=["samba"],
       aliases=["Jeeraga Samba", "Jeerakasamba", "Seeraga samba"], regions=TN,
       notes="Transplanted; 30–35 day nursery. Prized for biryani."),
    _v("Mappillai Samba", (155, 160), "Red", "traditional", TNAU_ITK_TRADITIONAL, seasons=["samba"],
       aliases=["Mapillai Samba", "Maappillai Samba", "Bridegroom rice"], regions=TN),
    _v("Thooyamalli", (135, 140), "Fine, white", "traditional", TNAU_ITK_TRADITIONAL, seasons=["samba"],
       aliases=["Thuyamalli", "Thooya Malli"], regions=TN),
    _v("Karuppu Kavuni", (150, 170), "Black", "traditional", TNAU_TN_VARIETIES, aliases=["Karuppukavuni", "Kavuni",
       "Black rice"], regions=TN, notes="Sown September–January; direct sowing (TNAU)."),
    _v("Kuzhi Vedichan", 110, "Bold, pale white", "traditional", TNAU_TN_VARIETIES, seasons=["samba"],
       regions=TN, notes="Coastal saline / sandy clay soils; tolerates salinity and drought."),
    _v("Val Sivappu", (145, 150), "Red", "traditional", TNAU_TN_VARIETIES, seasons=["thaladi"], regions=TN,
       notes="Saline and drought tolerant; tall (about 160 cm)."),
    _v("Soolai Kuruvai", (130, 140), "Bold, pale brown", "traditional", TNAU_TN_VARIETIES, regions=TN,
       notes="Coastal clay loam and saline soils."),
    _v("Kuthiraival Samba", (140, 150), "White", "traditional", TNAU_TN_VARIETIES, seasons=["samba"], regions=TN),
    _v("Mara Nel", (120, 125), "Red, coarse", "traditional", TNAU_TN_VARIETIES, seasons=["thaladi", "navarai"],
       regions=TN),
    _v("Pichavari", (110, 115), None, "traditional", TNAU_TN_VARIETIES, seasons=["thaladi"], regions=TN,
       notes="Tolerant to flood and drought."),
    _v("Gandhakasala", (150, 180), "Small, round, aromatic", "traditional", TNAU_KL_VARIETIES,
       aliases=["Gandhakasaala"], regions=["Kerala"], seasons_text="Kerala: Mundakan"),
    _v("Jeerakasala", (150, 180), "Slender, aromatic", "traditional", TNAU_KL_VARIETIES, regions=["Kerala"],
       seasons_text="Kerala: Mundakan"),
    _v("Njavara", (70, 75), "Brown seed coat (medicinal)", "traditional", TNAU_KL_VARIETIES, aliases=["Navara"],
       regions=["Kerala"], seasons_text="Kerala: Mundakan"),
]
